name: Extract ZIP File

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract Archive
        run: |
          mkdir -p extracted_files
          7z x PixelDeck-fixed-source.zip -oextracted_files/ -y

      - name: Upload Extracted Files
        uses: actions/upload-artifact@v4
        with:
          name: pixeldeck-extracted
          path: extracted_files/
